name: 04b Shells exercise
on: 
  push:
    branches:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
    running-lint-json:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Check node.js and npm version
              shell: bash
              run: |
                echo "Npm version: $(npm --version)"
                echo "Node.js version: $(node --version)"

            - name: Set libraries
              shell: bash
              run: |
                sudo apt-get update -y
                sudo apt-get install jsonlint -y

            - name: Check JSON files
              shell: bash
              run: |
                echo "Checking JSON files"
                echo "Current directory: $(pwd)"
                jsonlint-php package.json
