name: 05b - Expressions exercise
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
    runner-verifying:
        runs-on: ubuntu-latest
        steps:
            - name: Prepare output
              id: prepareOutput
              run: date >> ${{ runner.temp }}/output.log
            - name: SO information
              id: soInfo
              run: |
                echo "SO information:" >> ${{ runner.temp }}/output.log
                echo "- OS name: ${{ runner.os }}" >> ${{ runner.temp }}/output.log
                echo "- OS architecture: ${{ runner.arch }}" >> ${{ runner.temp }}/output.log
            - name: soInfo results
              run: |
                echo "Steps: ${{ toJson(steps) }}"
                echo "Results: $(cat ${{ runner.temp }}/output.log)"
