name: 05b - Expressions exercise
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
    runner-verifying:
        runs-on: ubuntu-latest
        steps:
            - name: Get SO information
              id: soInfo
              run: |
                echo "SO information:"
                echo "\t OS name: ${{ runner.os }}"
                echo "\t OS architecture: ${{ runner.arch }}"
            - name: Show SO information
              run: |
                echo "Steps: ${{ toJson(steps) }}"
                echo "Results: ${{ steps.soInfo.outputs.result }}"
