name: 06a - Variables and secrets
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    inputs:
        PILL_COLOR:
            description: 'Color of the pill'
            required: true
            default: 'blue'
            type: choice
            options:
              - blue
              - red
env:
    PILL_COLOR: ${{ inputs.PILL_COLOR || vars.PILL_COLOR || 'blue' }}
jobs:
    the-matrix:
        runs-on: ubuntu-latest
        steps:
        - name: Neo's election
          id: neo
          run: |
            echo "Neo has chosen the pill color: ${{ env.PILL_COLOR }}"
    
        - name: Know the truth
          if: ${{ env.PILL_COLOR == 'red' }}
          run: |          
            echo "I'll tell you the truth: ${{ secrets.EVERYTHING_IS_FAKE }}"
            echo "${{ secrets.EVERYTHING_IS_FAKE }}" | sed 's/./& /g'
            
        - name: Stay in the matrix
          if: ${{ env.PILL_COLOR == 'blue' }}
          run: |
              echo "You chose the blue pill, Neo. You will stay in the matrix."
              echo "You will continue to live in the illusion."