name: 06b - Vars and secrets exercise
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
    generate-random-integer:
        runs-on: ubuntu-latest
        steps:
            - name: Generate random integer
              id: generateRandomInteger
              run: |
                echo "randomInteger=$((1 + RANDOM % 10))" >> $GITHUB_ENV
            
            - name: Show random integer
              id: showRandomInteger
              run: |
                echo "Random integer generated: ${{ env.randomInteger }}"

            - name: Check if integer is even
              id: checkEven
              run: |
                if (( ${{ env.randomInteger }} % 2 == 0 )); then
                  echo "isEven=true" >> $GITHUB_ENV
                else
                  echo "isEven=false" >> $GITHUB_ENV
                fi

            - name: Integer is even
              if: ${{ env.isEven == 'true' }}
              run: echo "Integer ${{ env.randomInteger }} is even."
            
            - name: Integer is odd
              if: ${{ env.isEven == 'false' }}
              run: echo "Integer ${{ env.randomInteger }} is odd."
                