name: 07b - Input/Output exercise
on:
  workflow_dispatch:
    inputs:
      dices-order:
        description: 'Order of the dices'
        required: false
        default: one
        type: choice
        options:
          - one
          - two
jobs:
    roll-dices:
        runs-on: ubuntu-latest
        outputs:
            dice1: ${{ steps.rollOneDices.outputs.dice1 }}
            dice2: ${{ steps.rollTwoDices.outputs.dice2 }}
        steps:
            - name: Order of the dices.
              run: |
                echo "Dices order: ${{ inputs.dices-order }}"
            - name: Roll one dice
              id: rollOneDices
              shell: bash
              run: |
                dice1=$((1 + RANDOM % 6))
                echo "dice1=$dice1" >> $GITHUB_OUTPUT
                echo "$dice1"
            - name: Roll two dices
              if: ${{ inputs.dices-order == 'two' }}
              id: rollTwoDices
              shell: bash
              run: |
                dice2=$((1 + RANDOM % 6))
                echo "dice2=$dice2" >> $GITHUB_OUTPUT
                echo "$dice2"
            - name: Check results
              run: |
                echo "Steps: ${{ toJson(steps) }}"
    perform-dices-result:
      needs: roll-dices
      runs-on: ubuntu-latest
      steps:
        - name: Save rolled dices
          run: |
            echo "# :game_die: ROLL DICES GAME" >> $GITHUB_STEP_SUMMARY
            echo "### Roll dices result:" >> $GITHUB_STEP_SUMMARY
            echo "Saved rolled dices in step summary."
        - name: Save rolle dice 1
          run: |
            echo "- Dice 1: ${{ needs.roll-dices.outputs.dice1 }}" >> $GITHUB_STEP_SUMMARY
        - name: Save rolle dice 2
          if: ${{ inputs.dices-order == 'two' }}
          run: |
            echo "- Dice 2: ${{ needs.roll-dices.outputs.dice2 }}" >> $GITHUB_STEP_SUMMARY
    show-dices-result:
        runs-on: ubuntu-latest
        needs: roll-dices
        steps:
            - name: Show result
              run: |
                echo "Dice 1: ${{ needs.roll-dices.outputs.dice1 }}"
                if [[ ${{ inputs.dices-order == 'two' }} ]]; then
                    echo "Dice 2: ${{ needs.roll-dices.outputs.dice2 }}"
                    echo "Dices: $(( ${{ needs.roll-dices.outputs.dice1 }} + ${{ needs.roll-dices.outputs.dice2 }} ))"
                else
                    echo "Dices: ${{ needs.roll-dices.outputs.dice1 }}"
                fi
                
            - name: Show result in summary
              run: |
                echo "$GITHUB_STEP_SUMMARY"
