name: 16a - Code Inyection
description: Example of code inyection using GitHub Actions
on:
  issues:
    types: [opened]
jobs:
  inyection:
    name: Inyection example - successful hack
    runs-on: ubuntu-latest
    steps:
      - name: Show title
        run: |
          title="${{ github.event.issue.title }}"
          echo "${title}"
  avoid-inyection:
    name: Inyection example - successful hack
    runs-on: ubuntu-latest
    env:
      ISSUE_TITLE: ${{ github.event.issue.title }}
    steps:
      - name: Show title
        run: |
          echo "${ISSUE_TITLE}"